User test
ZProgrammers/ZStock_Backend pull request #7
Opened 2022-01-06 15:50 UTC by asefmostali

2022-01-06 20:14 UTC, aminkashiri requested changes
اکی بود همه چیش، فقط
related_name
ه
user  
توی 
PackagePurchase
رو درست نکردی. بذار 
package_purchases 
(مایگریشن یادت نره)
@asefmostali

2022-01-06 20:41 UTC, asefmostali commented
اره اونو درست کردم چون هم تست گرفتم هم سرور ران کردم چک کردم ولی احتمالا موقع مرجع برنچا اشتباه کردم یجا

2022-01-07 03:50 UTC, asefmostali commented
related_name  درست شد
migration انجام دادم
پروژه ران کردم همچیشو چک کردم
تست گرفتم اوکی بود 
یبار دیگه ریویو کن اگه مشکلی نداشت پوش کن

2022-01-07 06:03 UTC, aminkashiri reviewed
حله

2022-01-07 06:03 UTC, merged